### ISSUE TITLE
Feature proposal: Integrate with Conversations

### ISSUE THREAD

**Issue by funkyfuture** [gjedeer/paranoia#13]
hey, thanks for that useful addon.

however, is there a chance to integrate it with [the Conversations addon](https://addons.mozilla.org/de/thunderbird/addon/gmail-conversation-view/)? as of now, it doesn't display Paranoia's info.

**Comment by gjedeer** [comment]
It's a good idea and it should be doable by someone familiar with Conversations code.

I looked into it but it seems that with Conversations, the callback I'm using to know the message changed (onStartHeaders) isn't fired.

So if you want this implemented, maybe get in touch with the Conversations dev and ask how to implement such extension. Two major things to know are: name of the callback and name of DOM node to insert icon to.

I'm closing until then.
