### ISSUE TITLE
Official list of Recieved Methods

### ISSUE THREAD

**Issue by ladar** [gjedeer/paranoia#21]
I noticed you are missing a few "official" transfer types. The "official" IANA registry is here:

https://www.iana.org/assignments/mail-parameters/mail-parameters.xhtml#mail-parameters-7

Based on that list, you'll need to update this line:

https://github.com/gjedeer/paranoia/blob/b3ad1f8dc92f6ec6846414d08980c1036119c931/content/overlay.js#L59

**Comment by sdellenb** [comment]
I also just received an email via Mailgun (from an online shop) that has a Received header as follows:
```
Received: from so254-57.mailgun.net (so254-57.mailgun.net. [198.61.254.57])
        by mx.google.com with UTF8SMTPS id 189si10463739ioc.374.2017.10.03.02.28.02
        for <sdellenb@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Tue, 03 Oct 2017 02:28:02 -0700 (PDT)
```
`UTF8SMTPS` is mentioned in the IANA list linked above.

**Comment by gjedeer** [comment]
Thank you for your contribution @sdellenb (and for the tip @ladar). The new Paranoia is submitted for review now.

![selection_116](https://user-images.githubusercontent.com/315648/31294329-c4339432-aada-11e7-91ca-ec3ba3f6b6a2.png)

BTW, what's the latest TB version you guys have used with Paranoia? Mozilla wants me to tell them the latest tested version.

**Comment by sdellenb** [comment]
@gjedeer I'm using Thunderbird 52.3.0 (64-Bit) on macOS Sierra.

**Comment by gjedeer** [comment]
Thanks @sdellenb
