### ISSUE TITLE
Project inactive? / Thunderbird 68 compatibility

### ISSUE THREAD

**Issue by beerisgood** [gjedeer/paranoia#25]
Title.

**Comment by Hillside502** [comment]
No updates or 16 months  
https://addons.thunderbird.net/en-US/thunderbird/addon/paranoia/

It's looking that way!

**Comment by beerisgood** [comment]
I know, that's why i ask here.

**Comment by gjedeer** [comment]
Hmm, I've not been using Thunderbird for a long time now but I don't mind updating it for TB68. I just didn't know it's not working - glad @beerisgood reported.

I don't have a timeline though.

**Comment by gjedeer** [comment]
(of course, pull requests welcome)

**Comment by sdellenb** [comment]
@beerisgood Have you tried just updating the `maxVersion` similar to the latest commit (5e6330d) or is the extension completely broken?
I'm still on 60.9.0, so I can't test it.

**Comment by beerisgood** [comment]
@sdellenb i don't test that yet but it won't work if add-on isn't a webextension

**Comment by gjedeer** [comment]
Wait, so webextensions are now mandatory in Thunderbird too? I'm certainly not going to rewrite this as a WebExtension.

**Comment by gjedeer** [comment]
Looks like it's possible to just convert the manifest from RDF to JSON, anyone willing to give it a try?
https://developer.thunderbird.net/add-ons/updates/overlays

**Comment by beerisgood** [comment]
I try the convert and the install and addon itself works.
Only the config menu didn't open:
![error](https://user-images.githubusercontent.com/9625159/65284238-818a2580-db28-11e9-9a95-c6ac07bd44ad.png)


My manifest.json:

> {
  "manifest_version": 2,
  "applications": {
    "gecko": {
      "id": "tls-paranoia@gdr.name",
      "strict_min_version": "68.0"
    }
  },
  "name": "Paranoia",
  "description": "Check if your emails arrived encrypted (and which corporations were able to read them nevertheless)",
  "version": "0.2.7",
  "icons": {
    "32": "skin/good.png"
  },
  "legacy": {
    "type": "xul",
    "options": {
      "page": "chrome://Paranoia/content/overlay.xul",
      "open_in_tab": true
    }
  }
}

**Comment by gjedeer** [comment]
Nice!!! I don't think it had a settings page, maybe the 

     "options": {
       "page": "chrome://Paranoia/content/overlay.xul",
       "open_in_tab": true
     }

can be omitted?

Want to do a pull request with manifest.json or should I integrate it
myself?

**Comment by m-rey** [comment]
I've implemented the discussed changes and tested it on my Thunderbird installation.
There are no problems so far.
