### ISSUE TITLE
Microsoft TLS connection incorrectly marked insecure

### ISSUE THREAD

**Issue by wienfuchs** [gjedeer/paranoia#28]
anonymised header from relevant mail:

Received: from mail2.markeXXX (mail2.markeXXX [N.N.N.N])
	by MYHOST (Postfix) with ESMTPS id 0A0E... for <mail>; <date>
Received: from vmarkeXXX2 (192.168.31.161) by vMarketMail02.marketXXX
 (192.168.31.151) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256) id 15.1.1713.5; <date>

AFAIS this should not be marked as "insecure"

![paranoia-screen](https://user-images.githubusercontent.com/44177781/71908048-963d0880-316d-11ea-859c-cbc65433183b.png)

**Comment by gjedeer** [comment]
Hey, thanks for reporting, would you mind installing this version to see if it helps?

https://f.gdr.name/paranoia-issue-28.xpi

```
3c7217b875a578731ee65ff453cef45b6e6c2086d5e21cae8ac921008fc04ba3  ../paranoia.xpi
```

**Comment by wienfuchs** [comment]
Looks great, fixed this (uninstalling original xpi / reinstalling needed, but did it then)

**Comment by wienfuchs** [comment]
One more - ipv6 localhost probably should not require encrypted connection too;)

Received: from ip6-localhost ([::1] helo=pmamail.phpmyadmin.net)
	by mail.phpmyadmin.net with esmtp (Exim 4.89)
	(envelope-from <news-bounces@phpmyadmin>)
	id 1ioXRk-XXXX; Mon, 06 Jan 2020 19:49:51 +0100

**Comment by gjedeer** [comment]
Added, if you could download a copy at the same link and test IPv6 that would be great. Thanks!

```
0ab8b9d147ca6b513aad7613a97485070a9d3738250875ae61fb0c2a15303609  ../paranoia.xpi
```

**Comment by wienfuchs** [comment]
Looks very good also for this now:

![grafik](https://user-images.githubusercontent.com/44177781/71999572-f69d7a00-3241-11ea-8a08-95b2e6f04d7e.png)

**Comment by gjedeer** [comment]
Thanks for testing! I've submitted these changes as version 0.3.2.
