### ISSUE TITLE
Thunderbird 78 and 102

### ISSUE THREAD

**Issue by dougbreaux** [gjedeer/paranoia#29]
https://developer.thunderbird.net/add-ons/updating/tb78

**Comment by gitrazorhub** [comment]
This is an extremely useful add-on.  Would love to see it for TB 78.

**Comment by dougbreaux** [comment]
And now TB 102. 😭

**Comment by davoper** [comment]
Forked the repo and made some changes for it to work on Thunderbird 78+ (tested on current version 115)
Changed the Paranoia icon which was placed next to date field and made it into a button in the Reply, Forward... row of buttons - not ideal but at least it works :-)

See here:
https://github.com/davoper/paranoia-mailex/tree/mailex-port

**Comment by dougbreaux** [comment]
@davoper nice. Are you going to make a PR for it? @gjedeer would you take one?

**Comment by davoper** [comment]
Not sure it's ready to be merged yet, but you can try it out at least - there's an xpi package in my releases you can drag into add-ons screen in Thunderbird.

**Comment by gitrazorhub** [comment]
@davoper    
Is it me or is the api link not working?
https://gdr.geekhood.net/gdrwpl/heavy/paranoia.xpi

**Comment by gitrazorhub** [comment]
How does one install your addon if TB won't play ball?

**Comment by davoper** [comment]
Go to my releases page here:
https://github.com/davoper/paranoia-mailex/releases
Open Assets and right click on file paranoia-mailex_v0.4.0-beta.1.xpi then select
Save Link As... to save it on your Computer.
Open Thunderbird Add-ons page and drag/drop saved file into the list of add-ons

**Comment by gitrazorhub** [comment]
Thanks for the help.

**Comment by gjedeer** [comment]
Of course I will be happy to merge this PR.

**Comment by davoper** [comment]
Pull request created:
https://github.com/gjedeer/paranoia/pull/30

**Comment by gjedeer** [comment]
Nice! Thank you @davoper , I'm testing with Thunderbird 115 and it seems to work great. I've added provider icons, although maybe they could have a more fortunate placing, and removed some dead XUL-related code too.

**Comment by gjedeer** [comment]
I've submitted that to addons.thunderbird.net crediting your submission. Thank you again!

**Comment by gjedeer** [comment]
Just got an email

> Hello,
> 
> 
> Your add-on Paranoia has been updated on addons.thunderbird.net (ATN). Version 0.4.0 is now available for download in our gallery at https://addons.thunderbird.net/addon/paranoia/ .
> 
> This version has been screened and approved for the public. Keep in mind that other reviewers may look into this version in the future and determine that it requires changes or should be taken down. In that case, you will be notified again with details and next steps.
> 
> Thank you!
